export const GET_PROJECTS_ACTION = 'GET_PROJECTS';
export const SEND_PROJECT_ACTION = 'SEND_PROJECT';
export const UPDATE_PROJECT_ACTION = 'UPDATE_PROJECT';
export const DELETE_PROJECT_ACTION = 'DELETE_PROJECT';

// acoes das tarefas
export const GET_TASKS_ACTION = 'GET_TASKS';
export const SEND_TASK_ACTION = 'SEND_TASK';